### ISSUE TITLE
Some parameters show with decimals in the "Common Chorus" section E.g. Chorus Depth

### ISSUE THREAD

**Issue by christiansejer** [shimpe/Integra7AuralAlchemist#5]
Just a small thing. :-)

If you go to Common -> chorus for the studio set, then there are some parameters, that show with decimals at specific values. E.g. "Chorus Depth" and "Chorus Feedback" shows 122.000000 instead of 122 etc. 
This also seems to be the case for "Delay Left Level", "Delay Right Level", "Delay Center Level" and almost all parameters in "GM2 Chorus".
This also seems to be the case for most of the Common -> Reverb parameters. 

It might also be the case for other parameters, but these are the ones i have found so far.

Keep up the good work on this great software :-)

**Comment by shimpe** [comment]
Fixed in 07c772cde15a2e962979ad093276952a9e2740c6
